easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User

        Campagne:
            class: App\Entity\Campagne

        Event:
            class: App\Entity\Event